name: 'FTP-Deploy'
description: 'A GitHub Action that deploys via FTP'
inputs:
  server:
    required: true
    description: "ftp server"
  username:
    required: true
    description: "ftp username"
  password:
    required: true
    description: "ftp password"
  port:
    required: false
    default: 21
    description: "Server port to connect to"
  local-dir:
    required: false
    description: "Folder to upload from."
  server-dir:
    required: false
    description: "Path to upload to on the server."
  data-file:
    required: false
    description: "Path to the file in which to store file checksums"
    default: deploy-data/files.json
runs:
  using: 'composite'
  steps:
    - name: Check directory
      run: |
        pwd
        ls
        echo $ACTION_PATH
        ls $ACTION_PATH
      env:
        ACTION_PATH: ${{ github.action_path }}
      shell: bash
    - name: Checkout
      uses: actions/checkout@v4
    - name: Check directory
      run: |
        pwd
        ls
        echo $ACTION_PATH
        ls $ACTION_PATH
      env:
        ACTION_PATH: ${{ github.action_path }}
      shell: bash
    - name: Install Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'  
    - name: Install Dependencies
      run: pip install -r $ACTION_PATH/requirements.txt
      shell: bash
      env:
        ACTION_PATH: ${{ github.action_path }}
    - name: Fetch the number's square
      id: get-square
      run: python $ACTION_PATH/src/main.py
      shell: bash
      env:
        ACTION_PATH: ${{ github.action_path }}
        INPUT_SERVER: ${{ inputs.server }}
        INPUT_USERNAME: ${{ inputs.username }}
        INPUT_PASSWORD: ${{ inputs.password }}
        INPUT_PORT: ${{ inputs.port }}
        INPUT_LOCAL_DIR: ${{ github.action_path }}/${{ inputs.local-dir }}
        INPUT_SERVER_DIR: ${{ inputs.server-dir }}
        INPUT_DATA_FILE: ${{ inputs.data-file }}
