name: 'FTP-Deploy'
description: 'A GitHub Action that deploys via FTP'
inputs:
  server:
    required: true
    description: "ftp server"
  username:
    required: true
    description: "ftp username"
  password:
    required: true
    description: "ftp password"
  port:
    required: false
    default: 21
    description: "Server port to connect to (read your web hosts docs)"
  local-dir:
    required: false
    description: "Folder to upload from, must end with trailing slash /"
  server-dir:
    required: false
    description: "Path to upload to on the server. Must end with trailing slash /"
runs:
  using: 'composite'
  steps:
    - name: Install Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'  
    - name: Install Dependencies
      run: pip install -r requirements.txt
      shell: bash
    - name: Fetch the number's square
      id: get-square
      run: python src/main.py
      shell: bash
      env:
        INPUT_SERVER: ${{ inputs.server }}
        INPUT_USERNAME: ${{ inputs.username }}
        INPUT_PASSWORD: ${{ inputs.password }}
        INPUT_PORT: ${{ inputs.port }}
        INPUT_LOCAL_DIR: ${{ inputs.local-dir }}
        INPUT_SERVER_DIR: ${{ inputs.server-dir }}
