# .github/workflows/test_action.yaml
name: Test Action
on: [push]

jobs:
  get-num-square:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Fetch num squared
        id: get_square
        uses: ./
        with:
          server: ${{secrets.ftp_server}}
          username: ${{secrets.ftp_username}}
          password: ${{secrets.ftp_password}}
